### ISSUE TITLE
`optional` breaks when ActiveSupport's `try` is present

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-struct#26] opened 2016-12-23 08:33 UTC
Context: https://github.com/rom-rb/rom-sql/issues/115#issuecomment-267765229

**Comment by gottfrois** [comment] 2017-01-11 17:33
Would like to add another issue I encountered when using `try`:

```ruby
require 'dry-struct'

class Foo < Dry::Struct
end
```

```
foo = Foo.new
> foo.class
 => Foo
foo.class.name
 => "Foo"
foo.class.try(:name)
TypeError: can't convert Symbol into Hash
from /Users/gottfrois/.rvm/gems/ruby-2.3.3/gems/dry-types-0.9.3/lib/dry/types/constructor.rb:39:in `Hash'
from /Users/gottfrois/.rvm/gems/ruby-2.3.3/gems/dry-types-0.9.3/lib/dry/types/constructor.rb:39:in `[]'
from /Users/gottfrois/.rvm/gems/ruby-2.3.3/gems/dry-types-0.9.3/lib/dry/types/constructor.rb:39:in `call'
from /Users/gottfrois/.rvm/gems/ruby-2.3.3/gems/dry-struct-0.1.1/lib/dry/struct/class_interface.rb:77:in `new'
from /Users/gottfrois/.rvm/gems/ruby-2.3.3/gems/dry-struct-0.1.1/lib/dry/struct/class_interface.rb:92:in `try'
```

**Comment by solnic** [comment] 2017-01-11 17:49
@gottfrois looks like for some reason `rescue Struct::Error` doesn't work even though `StructError = Class.new(TypeError)`

**Comment by gottfrois** [comment] 2017-01-12 09:26
Correct, if I explicitely `rescue TypeError` it catches the exception and return

```
Foo.new.class.try(:to_s)
 => #<Dry::Types::Result::Failure input=:to_s error="can't convert Symbol into Hash">
```

However, isn't this supposed to work? Calling `to_s` on `Foo.new.class` should return `"Foo"` in this case no? What's up with the `try` override here?

**Comment by solnic** [comment] 2017-01-12 09:36
@gottfrois `Dry::Types#try` is an interface for processing input by a type object in a safe way, it's not for calling methods like in ActiveSupport

**Comment by gottfrois** [comment] 2017-01-12 09:43
I see, that's ennoying :-/ It conflicts pretty badly with active support here in my case. I have this value object which inherits from `Struct` in a rails app and calling `try` on it happen in places I don't own... Any suggestions on how to avoid this?

**Comment by flash-gordon** [comment] 2017-01-12 10:01
@gottfrois you can just override it like this
```ruby
def self.try(m, *args)
  if m.is_a?(Symbol)
    public_send(m, *args)
  else
    super
  end
end

**Comment by gottfrois** [comment] 2017-01-12 10:06
thx for the tip!

**Comment by flash-gordon** [comment] 2017-04-30 12:54
I cannot reproduce this, @mrship do you remember how that happened? :)

**Comment by mrship** [comment] 2017-05-02 18:29
I'll see if I can create a test case.

**Comment by mrship** [comment] 2017-05-02 19:48
This is using rom as well as dry-struct as this is a close as I could get to my original setup. If I use 
`attribute :snapshot, Types::Snapshot.optional` then this blows with:

```
/Users/shipmana/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-types-0.10.2/lib/dry/types/sum.rb:82:in `block in try': undefined method `try' for Types::Snapshot:Class (NoMethodError)
```

When I was using activesupport, it would end up in that gem's `try` method. Here though it just blows up, as I couldn't get it to fall into activesupport. However, if I use the commented line (below) instead, e.g. `attribute :snapshot, Types::Snapshot.default { nil }` then it works as expected.

```ruby
#!/usr/bin/env ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'rom'
  gem 'rom-sql'
  gem 'rom-repository'
  gem 'dry-types'
  gem 'sequel', "=4.45"
  gem 'sqlite3'
end

require 'rom-sql'
require 'rom-repository'
require 'dry-types'

module Types
  include Dry::Types.module

  class Snapshot
    extend Dry::Types::Builder
    def self.construct(element)
      element
    end

    def self.constrained?
      false
    end

    def self.[](attribute)
      construct(attribute)
    end
  end

  Dry::Types.register_class(Snapshot, :construct)
end

class Question < Dry::Struct
  constructor_type :schema
  attribute :snapshot, Types::Snapshot.optional
  # attribute :snapshot, Types::Snapshot.default { nil }
end

rom = ROM.container(:sql, 'sqlite::memory') do |c|
  c.gateways[:default].create_table :snapshots do
    primary_key :id, Integer
    column :question_id, Integer
    column :name, String
  end

  c.gateways[:default].create_table :questions do
    primary_key :id, Integer
    column :name, String
  end

  c.gateways[:default].use_logger(Logger.new($stdout))

  c.relation(:questions) do
    schema(:questions, infer: false) do
      attribute :id, Types::Int.meta(primary_key: true)
      attribute :name, Types::String

      associations do
        has_one :snapshot
      end
    end
  end
end

question = rom.relations[:questions].insert(name: "What's the meaning of life?")
rom.relations[:snapshots].insert(name: "42", question_id: question)

class QuestionRepo < ROM::Repository[:questions]
  relations :snapshots

  def query
    aggregate(:snapshot).as(Question).to_a
  end
end

repo = QuestionRepo.new(rom)

puts repo.query.to_a.inspect
```

**Comment by flash-gordon** [comment] 2017-05-04 18:14
@mrship thank you, this was very helpful
You're doing it wrong :) `Types::Snapshot` is not a type from `dry-t`'s perspective, extending it with `Builder` is not enough. `dry-struct` does the trick by implementing the whole type interface, but it's not required in your case. What you need is to use the type instance created by that `register_class` call:

```ruby
class Question < Dry::Struct
  constructor_type :schema
  attribute :snapshot, Dry::Types['types.snapshot'].optional
  # attribute :snapshot, Types::Snapshot.default { nil }
end
```

I'm closing this, but feel free to ask for any clarifications

**Closed by flash-gordon** 2017-05-04 18:14 UTC
Labels: bug
