### ISSUE TITLE
Inappropriate exception when coercible int not present

### ISSUE THREAD

**Issue by jtippett** [dry-rb/dry-struct#29] opened 2017-02-08 12:07 UTC
Consider this example:

```ruby
2.4.0 :021 > class Item < Dry::Struct
2.4.0 :022?>   attribute :price, Types::Coercible::Int
2.4.0 :023?> end
 => Item 
2.4.0 :024 > i = Item.new
TypeError: can't convert nil into Integer
```

I would expect an error along these lines instead:

`Dry::Struct::Error: [Item.new] :price is missing in Hash input`

Is there a way to run the missing check first, before attempting to coerce?

**Comment by Kukunin** [comment] 2017-02-08 12:57
Struct requires to have any attribute key in constructor hash, even if it's optional. Otherwise it raises exception. 

This is by design and useful in cases, when you made a typo in attribute key, for example. 

You can override that behaviour with different `constructor_type`: take a look here http://dry-rb.org/gems/dry-types/hash-schemas/

```ruby
class Item < Dry::Struct
  constructor_type :schema

  attribute :price, Types::Coercible::Int
end

Item.new.price # => should be nil here
```

**Comment by jtippett** [comment] 2017-02-08 13:02
Yes, it is expected and by design that it raises when an attribute is missing. The point I was trying to make is that the exception is incorrect.

Expected:

`Dry::Struct::Error: [Item.new] :price is missing in Hash input
`
Actual:

`TypeError: can't convert nil into Integer`

Sorry for not being more clear!

**Comment by flash-gordon** [comment] 2017-02-08 13:26
```ruby
gordon@oss ~/dev/dry-rb/dry-struct [master] $ ./bin/console
2.3.1 :001 > Item = Class.new(Dry::Struct) { attribute :price, Dry::Types['coercible.int'] }
 => Item
2.3.1 :002 > Item.new
TypeError: can't convert nil into Integer
	from /Users/gordon/.rvm/gems/ruby-2.3.1@dry-struct/gems/dry-types-0.9.1/lib/dry/types/constructor.rb:28:in `Integer'
2.3.1 :003 > Item.new({})
Dry::Struct::Error: [Item.new] :price is missing in Hash input
	from /Users/gordon/dev/dry-rb/dry-struct/lib/dry/struct/class_interface.rb:80:in `rescue in 2.3.1 :004 >
```
@backus don't you think it would have identical behaviors in these^ cases? E.g. we could make `default_attributes` to skip non-default types

**Comment by solnic** [comment] 2017-02-26 14:27
I marked it as a bug. I *think* we want to remove defaulting to empty attributes in the constructor.

**Closed** 2017-04-30 13:27 UTC
Labels: bug
